### ISSUE TITLE
mvn clean package failed

### ISSUE THREAD

**Issue by vkjuju** [oracle-devrel/springai-rag-db23ai#5]
Hi Sir, 
We hit the following error message, any advice would be appreciated:

[oracle@localhost springai-rag-db23ai-main]$ mvn clean package -Dmaven.test.skip=true
[INFO] Scanning for projects...
Downloading from spring-snapshots: https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-parent/3.2.0/spring-boot-starter-parent-3.2.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/3.2.0/spring-boot-starter-parent-3.2.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.example:demoai:0.0.1-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:3.2.0 from/to spring-snapshots (https://repo.spring.io/snapshot): repo.spring.io: Name or service not known and 'parent.relativePath' points at no local POM @ line 6, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.example:demoai:0.0.1-SNAPSHOT (/home/oracle/Downloads/springai-rag-db23ai-main/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.example:demoai:0.0.1-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:3.2.0 from/to spring-snapshots (https://repo.spring.io/snapshot): repo.spring.io: Name or service not known and 'parent.relativePath' points at no local POM @ line 6, column 10: Unknown host repo.spring.io: Name or service not known -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by jasperan** [comment]
Hi @vkjuju , is this the same issue you mentioned via email?

**Comment by jasperan** [comment]
Resolved via email
